swagger: "2.0"

info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "2.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v2
schemes:
  - http
paths:

  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /accounts/{userID}:
    post:
      security:
        - Bearer: []
      tags:
        - Money Module
      summary: Get User Accounts
      description: API for retrieving accounts associated with a user
      parameters:
        - in: path
          name: userID
          description: ID of the user
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Accounts retrieved successfully
          schema:
            $ref: "#/definitions/AccountsResponse"
        "400":
          description: Invalid Fields or Incorrect userID
        "500":
          description: Internal Server Error

  /transactions/{accountID}:
    post:
      security:
        - Bearer: []
      tags:
        - Money Module
      summary: Get Account Transactions
      description: API for retrieving transactions associated with an account
      parameters:
        - in: path
          name: accountID
          description: ID of the account
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid Fields or Incorrect AccountID
        "500":
          description: Internal Server Error

  /transactions/{transactionID}:
    put:
      security:
        - Bearer: []
      tags:
        - Money Module
      summary: Update Transaction Details
      description: API for updating transaction details
      parameters:
        - in: path
          name: transactionID
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Updated transaction details
          required: true
          schema:
            $ref: "#/definitions/UpdatedTransactionDetails"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details updated successfully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid Fields or Incorrect TransactionID
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
      userID:
        type: string
        description: user unique ID

  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      userName:
        type: string

  AccountsResponse:
    type: array
    items:
      type: object
      properties:
        accountID:
          type: string
          description: Account ID
        type:
          type: string
          description: Type of account (e.g., Checking, Savings, Credit Card)
        balance:
          type: string
          description: Balance of the account
        description:
          type: string
          description: Description of the account balance (e.g., Available Balance, Current Balance)

  TransactionsResponse:
    type: array
    items:
      type: object
      properties:
        transactionID:
          type: string
          description: unique ID of the transaction
        date:
          type: string
          format: date-time
          description: Date and time of the transaction
        description:
          type: string
          description: Description of the transaction
        amount:
          type: string
          description: Amount of the transaction
        balance:
          type: string
          description: Balance after the transaction
        details:
          type: object
          properties:
            type:
              type: string
              description: Type of transaction (e.g., Electronic)
            category:
              type: string
              description: Category of the transaction
            notes:
              type: string
              description: Additional notes about the transaction

  UpdatedTransactionDetails:
    type: object
    properties:
      category:
        type: string
        description: Updated category of the transaction
      notes:
        type: string
        description: Updated notes for the transaction
